version: '3.5'

services:
  api:
    container_name: api_container
    build:
      context: ./
    environment:
      DB_CONNECTION: "User ID=Batteries;Password=123456789;Host=postgres;Port=5432;Database=Batteries;Pooling=true;"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORT: https://+:3001
      ASPNETCORE_URLS: http://+:3000
    ports:
      - "3001:3001"
      - "3000:3000"
    networks:
      - batteries
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: Batteries
      POSTGRES_PASSWORD: 123456789
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - batteries
    restart: unless-stopped
    

networks:
  batteries:
    driver: bridge

volumes:
  postgres: